version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: bonlivre
      POSTGRES_PASSWORD: d0stO1evSky
      POSTGRES_DB: bonlivredb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - bonlivre-network

  minio:
    image: docker.io/bitnami/minio:2022
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'

networks:
  bonlivre-network:
    driver: bridge

volumes:
  bonlivre-volume:
    driver: locals
  minio_data:
    driver: local
