version: "3.4"

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - minio
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio
    ports:
      - 9000:9000
      - 9001:9001
